# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
  # Node install
  - task: NodeTool@0
    displayName: Node install
    inputs:
      versionSpec: '10.x' # The version we're installing

  # Write the installed version to the command line
  - script: which node
  
  - script: cd $(Build.Repository.LocalPath)

  - script: npm install 

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.Repository.LocalPath)'
      artifactName: drop
