# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
  # - script: cd $(Build.Repository.LocalPath)

  - script: npm install $(Build.Repository.LocalPath)

  # These delete files tasks fail silently if the file doesn't exist
  - task: DeleteFiles@1
    inputs:
      contents: '$(Build.Repository.LocalPath)/local.settings.json' 

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.Repository.LocalPath)' 
      includeRootFolder: false
      archiveType: 'zip' # Options: zip, 7z, tar, wim
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip' 
      replaceExistingArchive: true 
      
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      artifactName: drop
