# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- staging
pr:
- master
- staging

pool:
  vmImage: 'Ubuntu-16.04'

steps:
  - script: npm i 
  - script: npm i -g apollo
  - script: npm i -g azure-functions-core-tools --unsafe-perm true
  - script: func start
  - script: apollo service:check --endpoint:"http://localhost:7071/api/graphql" --tag=staging --key=service:usgs-graphql-api:R84LYC5fMohpkfy_b7VIaw

  # These delete files tasks fail silently if the file doesn't exist
  - task: DeleteFiles@1
    inputs:
      contents: 'local.settings.json' 
  - task: DeleteFiles@1
    inputs: 
      contents: 'azure-pipelines.yml'
  - task: DeleteFiles@1
    inputs: 
      contents: 'README.md'
  - task: DeleteFiles@1
    inputs: 
      contents: '.gitignore'
  - task: DeleteFiles@1
    inputs: 
      contents: '.gitattributes'
  - task: DeleteFiles@1
    inputs: 
      contents: '.git'
  - task: DeleteFiles@1
    inputs: 
      contents: '.vscode'

  # Staging
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.Repository.LocalPath)' 
      includeRootFolder: false
      archiveType: 'zip' 
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip' 
      replaceExistingArchive: true 

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      artifactName: drop